## 2장. 국내 주식 분석하기

Colab에서 실행하기 :
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/DrFirstLee/python_investments_notebooks/blob/main/1장_실습_v01.ipynb)

### 2.1 데이터 수집하기

멀티팩터 라이브러리 설치

In [ ]:
!pip install MultiFactor
#!pip install --upgrade MultiFactor   # 기존 설치된 라이브러리를 최신으로 업데이트

라이브러리 불러오기

In [2]:
# 라이브러리 불러오기
from MultiFactor import MultiFactorKR

# 멀티팩터 객체 생성: 시가총액 상위 5개 종목 추출
mf_kr = MultiFactorKR(N=5)

# 멀티팩터 종합점수 산출
mf_kr.get_score()

(1/5) 종목코드 생성
종목 추출 건수  5

(2/5) 모멘텀 지표 생성

(3/5) 밸류 지표 생성
0/5 진행 중... (삼성전자)

(4/5) 퀄리티 지표 생성
0/5 진행 중... (삼성전자)

(5/5) 멀티팩터 마스터 생성

,scode,sname,mom_price,mom_vol,PER,PBR,revenue_rate,oper_income_rate,net_income_rate,ROE,...,모멘텀_거래량,밸류_PER,밸류_PBR,퀄리티_ROE,퀄리티_매출증가,퀄리티_영업이익증가,퀄리티_순이익증가,종합점수,종합순위,종합순위_퍼센트
0,402340,SK스퀘어,162.793694,-13.520411,5.54,1.73,9.757049,17.123417,32.005317,37.08,...,80.0,20.0,40.0,40.0,40.0,60.0,40.0,42.5,1.0,20.0
1,000660,SK하이닉스,137.147128,-12.919755,11.03,3.73,34.266572,68.399599,21.024013,44.14,...,60.0,60.0,100.0,20.0,20.0,20.0,60.0,47.5,2.0,40.0
2,005930,삼성전자,71.544114,-18.360558,17.89,1.82,9.035030,64.997000,60.659103,10.78,...,100.0,80.0,60.0,60.0,60.0,40.0,20.0,60.0,3.0,60.0
3,005380,현대차,35.440521,2.516382,7.65,0.61,0.250849,-33.180940,-53.535829,8.36,...,40.0,40.0,20.0,80.0,100.0,80.0,80.0,65.0,4.0,80.0
4,373220,LG에너지솔루션,19.704488,53.139571,1067.15,2.94,7.747504,-292.917727,-244.096251,0.27,...,20.0,100.0,80.0,100.0,80.0,100.0,100.0,85.0,5.0,100.0

#### 2.1.1 종목의 기초 정보 수집하기

FinanceDataReader 라이브러리 설치

In [35]:
!pip install finance-datareader

1

FinanceDataReader와 pandas 라이브러리 불러오기

In [4]:
import FinanceDataReader as fdr
import pandas as pd

코스피 종목 정보 추출

In [5]:
# 코스피 종목 정보 수집
df = fdr.StockListing('KOSPI')

# 종목코드, 종목명, 시가총액만 선택
df = df[['Code','Name','Marcap']]

# 최초 5건 화면 출력
df.head()

     Code      Name            Marcap
0  005930      삼성전자  1283258154456000
1  000660    SK하이닉스   870922290030000
2  005935     삼성전자우   123324453901100
3  373220  LG에너지솔루션   112554000000000
4  005380       현대차   105040733958000

코스닥 종목 정보 추출

In [6]:
# 코스닥 종목 정보 수집
df = fdr.StockListing('KOSDAQ')

# 종목코드(Code), 종목명(Name), 시가총액(Marcap)만 선택
df = df[['Code','Name','Marcap']]

# 최초 5건 화면 출력
df.head()

     Code      Name          Marcap
0  086520      에코프로  21262545403200
1  247540    에코프로비엠  20348730272000
2  196170      알테오젠  19753988067000
3  277810  레인보우로보틱스  11872713096000
4  000250     삼천당제약   9652749728000

#### 2.1.1 모멘텀 지표

삼성전자의 25.4.16~25.4.18 주가

In [7]:
fdr.DataReader('005930', '20250416', '20250418')

             Open   High    Low  Close    Volume    Change
Date
2025-04-16  56000  56200  54500  54700  14437025 -0.033569
2025-04-17  54700  55300  54500  55100  10867069  0.007313
2025-04-18  55300  55600  54900  55300   5848342  0.003630

삼성전자의 주가 등락률

In [8]:
# 삼성전자 1년치 주가 데이터
df = fdr.DataReader('005930', '20240418', '20250418')

# 전일
mom_1d = ( df.iloc[-1]['Close'] / df.iloc[-2]['Close'] - 1 ) * 100
# 주간
mom_1w = ( df.iloc[-1]['Close'] / df.iloc[-5]['Close'] - 1 ) * 100
# 월간
mom_1m = ( df.iloc[-1]['Close'] / df.iloc[-20]['Close'] - 1 )  * 100
# 연간
mom_1y = ( df.iloc[-1]['Close'] / df.iloc[-240]['Close'] - 1 )  * 100

In [9]:
# 전일
mom_1d

np.float64(0.3629764065335772)

In [10]:
# 전주
mom_1w

np.float64(-1.6014234875444844)

In [11]:
# 전월
mom_1m

np.float64(-8.595041322314046)

In [12]:
# 전년
mom_1y

np.float64(-26.75496688741722)

In [14]:
# 주가 등락률 계산
mom = (mom_1d + mom_1w + mom_1m + mom_1y) /4
mom

np.float64(-9.147113822685544)

거래량 변동성

In [16]:
# 거래량 5일 이동평균의 마지막 데이터
vol_short = df['Volume'].rolling(window=5).mean().iloc[-1]

# 거래량 20일 이동평균의 마지막 데이터
vol_long = df['Volume'].rolling(window=20).mean().iloc[-1]

# 거래량 변동성 계산
vol = ( vol_short / vol_long - 1) * 100
vol

np.float64(-37.89028795307283)

#### 2.1.3 밸류 지표

삼성전자 재무 데이터 추출

In [17]:
# 재무제표 데이터 추출
data = fdr.SnapDataReader('NAVER/FINSTATE-2Y/005930')

# 미래 추정치 제외(영업이익 결측치 삭제)
data = data.dropna(subset='영업이익')

# PER, PBR 출력
data[['PER(배)', 'PBR(배)']]

주요재무정보      PER(배)  PBR(배)
날짜
2021-12-01   13.33    1.74
2022-12-01    6.75    1.06
2023-12-01   34.43    1.47
2024-12-01   10.49    0.89
2025-12-01   17.89    1.82

In [18]:
# PER의 가장 최근 데이터
print(data['PER(배)'].iloc[-1])

17.89

In [19]:
# PBR의 가장 최근 데이터
print(data['PBR(배)'].iloc[-1])

1.82

#### 2.1.4 퀄리티 지표

퀼리티 데이터 추출하기 (삼성전자)

In [20]:
# 대상 칼럼 지정
cols = ['매출액', '영업이익', '당기순이익', 'ROE(%)']

# 재무 데이터 추출: 분기 K-IFRS 연결 기준
data = fdr.SnapDataReader('NAVER/FINSTATE-2Q/005930')[cols]

# 미래 추정치 제외: 영업이익 결측치 삭제
data = data.dropna(subset='영업이익')

# 결과 화면 출력
data

주요재무정보           매출액      영업이익     당기순이익  ROE(%)
날짜
2024-12-01  757883.0   64927.0   77544.0    9.00
2025-03-01  791405.0   66853.0   82229.0    9.23
2025-06-01  745663.0   46761.0   51164.0    7.97
2025-09-01  860617.0  121661.0  122257.0    8.33
2025-12-01  938374.0  200737.0  196417.0   10.78

퀄리티 지표 생성하기

In [21]:
# 매출액증가율, 영업이익증가율, 당기순이익증가율
(data[['매출액','영업이익','당기순이익']].pct_change()*100).iloc[-1].to_list()

[9.035029519519133, 64.99699986026745, 60.659103364224556]

In [22]:
# ROE (최근시점)
data['ROE(%)'].iloc[-1]

np.float64(10.78)

---
## 2.2 멀티팩터 생성하기

#### 2.2.3 종합지표 생성하기

In [24]:
# 멀티팩터 객체 생성: 시가총액 상위 10개 종목 추출
mf_kr = MultiFactorKR(N=10)

# 멀티팩터 종합점수 산출해 데이터프레임(df)에 저장
df = mf_kr.get_score()

(1/5) 종목코드 생성
종목 추출 건수  10

(2/5) 모멘텀 지표 생성

(3/5) 밸류 지표 생성
0/10 진행 중... (삼성전자)

(4/5) 퀄리티 지표 생성
0/10 진행 중... (삼성전자)

(5/5) 멀티팩터 마스터 생성

In [25]:
# 종합지표 원본 칼럼명 정의
cols = ['scode', 'sname', 'mom_price', 'mom_vol', 'PER', 'PBR',
        'revenue_rate', 'oper_income_rate', 'net_income_rate', 'ROE']

# 상위 5개 종목 결과 출력
df[cols].head()

,scode,sname,mom_price,mom_vol,PER,PBR,revenue_rate,oper_income_rate,net_income_rate,ROE
0,000660,SK하이닉스,137.147128,-12.919755,11.03,3.73,34.266572,68.399599,21.024013,44.14
1,402340,SK스퀘어,162.793694,-13.520411,5.54,1.73,9.757049,17.123417,32.005317,37.08
2,005930,삼성전자,71.544114,-18.360558,17.89,1.82,9.035030,64.997000,60.659103,10.78
3,012450,한화에어로스페이스,24.508224,-14.709774,21.01,2.88,29.826563,-5.698272,39.567537,15.57
4,329180,HD현대중공업,30.711272,45.212318,32.42,5.72,17.546798,3.176027,13.649025,18.82

In [26]:
#  종합지표 순위 칼럼명 정의
cols = ['scode', 'sname',  '모멘텀_주가', '모멘텀_거래량', '밸류_PER', '밸류_PBR',
             '퀄리티_ROE', '퀄리티_매출증가', '퀄리티_영업이익증가', '퀄리티_순이익증가']

# 상위 5개 종목 결과 출력
df[cols].head()

,scode,sname,모멘텀_주가,모멘텀_거래량,밸류_PER,밸류_PBR,퀄리티_ROE,퀄리티_매출증가,퀄리티_영업이익증가,퀄리티_순이익증가
0,000660,SK하이닉스,20.0,60.0,40.0,70.0,10.0,10.0,10.0,40.0
1,402340,SK스퀘어,10.0,70.0,10.0,30.0,20.0,50.0,50.0,30.0
2,005930,삼성전자,40.0,100.0,50.0,40.0,70.0,60.0,20.0,10.0
3,012450,한화에어로스페이스,70.0,80.0,60.0,50.0,50.0,20.0,70.0,20.0
4,329180,HD현대중공업,60.0,20.0,70.0,90.0,40.0,40.0,60.0,50.0

In [27]:
# 종합점수/순위 칼럼명 정의
cols = ['scode', 'sname', '종합점수', '종합순위', '종합순위_퍼센트']

# 상위 5개 종목 결과 출력
df[cols].head()

    scode      sname   종합점수  종합순위  종합순위_퍼센트
0  000660     SK하이닉스  32.50   1.0      10.0
1  402340      SK스퀘어  33.75   2.0      20.0
2  005930       삼성전자  48.75   3.0      30.0
3  012450  한화에어로스페이스  52.50   4.0      40.0
4  329180    HD현대중공업  53.75   5.0      50.0

In [28]:
# 데이터프레임의 종목들을 종합점수 상위 순으로 3개(Ngroup=3)의 그룹으로 나눔
mf_kr.get_Ngroup(df, Ngroup=3)

1 : SK하이닉스, SK스퀘어, 삼성전자, 한화에어로스페이스
2 : HD현대중공업, 현대차, 기아
3 : 두산에너빌리티, 삼성바이오로직스, LG에너지솔루션

#### 2.2.4 종합지표 최적화하기

투자 스타일별 종합지표 최적화

시가총액 상위 100종목 추출

In [34]:
1# 멀티팩터 객체 생성: 시가총액 상위 100 종목
mf_kr = MultiFactorKR(N=100)

# 멀티팩터 종합점수 산출하여 데이터프레임(df)에 저장
df = mf_kr.get_score()

1

가치 성장 전략

In [31]:
cols = ['scode', 'sname', '모멘텀_주가', '모멘텀_거래량', '밸류_PER', '밸류_PBR',
             '퀄리티_ROE', '퀄리티_매출증가', '퀄리티_영업이익증가', '퀄리티_순이익증가',
             '종합점수', '종합순위', '종합순위_퍼센트']

# 가치 성장 전략 적용(밸류 + 퀄리티 조합)
data = mf_kr.get_score_adj_weight(df, weight='가치성장')

# 최상위 5종목 출력
data[cols].head()

,scode,sname,모멘텀_주가,모멘텀_거래량,밸류_PER,밸류_PBR,퀄리티_ROE,퀄리티_매출증가,퀄리티_영업이익증가,퀄리티_순이익증가,종합점수,종합순위,종합순위_퍼센트
0,006800,미래에셋증권,9.090909,89.898990,27.272727,40.404040,29.292929,16.161616,2.020202,13.131313,21.380471,1.0,1.010101
1,028050,삼성E&A,26.262626,97.979798,16.161616,41.414141,22.222222,13.131313,13.131313,25.252525,21.885522,2.0,2.020202
2,000660,SK하이닉스,6.060606,69.696970,28.282828,73.737374,2.020202,14.141414,7.070707,26.262626,25.252525,3.0,3.030303
3,267250,HD현대,25.252525,27.272727,3.030303,7.575758,27.272727,61.616162,33.333333,19.191919,25.336700,4.0,4.040404
4,005830,DB손해보험,52.525253,42.424242,6.060606,27.272727,19.191919,44.444444,29.292929,29.292929,25.925926,5.0,5.050505

추세 성장 전략

In [32]:
# 출력 칼럼 정의
cols = ['scode', 'sname',  '모멘텀_주가', '모멘텀_거래량', '밸류_PER', '밸류_PBR',
             '퀄리티_ROE', '퀄리티_매출증가', '퀄리티_영업이익증가', '퀄리티_순이익증가',
             '종합점수', '종합순위', '종합순위_퍼센트']

# 추세 성장 전략 적용(모멘텀 + 퀄리티 조합)
data = mf_kr.get_score_adj_weight(df, weight='추세성장')

# 최상위 5종목 출력
data[cols].head()

,scode,sname,모멘텀_주가,모멘텀_거래량,밸류_PER,밸류_PBR,퀄리티_ROE,퀄리티_매출증가,퀄리티_영업이익증가,퀄리티_순이익증가,종합점수,종합순위,종합순위_퍼센트
0,010120,LS ELECTRIC,7.070707,7.070707,81.818182,84.848485,24.242424,24.242424,21.212121,24.242424,18.013468,1.0,1.010101
1,267260,HD현대일렉트릭,16.161616,19.191919,74.747475,94.949495,3.030303,30.303030,20.202020,23.232323,18.686869,2.0,2.020202
2,000660,SK하이닉스,6.060606,69.696970,28.282828,73.737374,2.020202,14.141414,7.070707,26.262626,20.875421,3.0,3.030303
3,011070,LG이노텍,11.111111,15.151515,59.595960,44.444444,63.636364,11.111111,10.101010,34.343434,24.242424,4.0,4.040404
4,052690,한전기술,29.292929,32.323232,78.787879,79.797980,23.232323,3.030303,5.050505,55.555556,24.747475,5.0,5.050505

역발상 전략

In [33]:
# 출력 칼럼 정의
cols = ['scode', 'sname',  '모멘텀_주가', '모멘텀_거래량', '밸류_PER', '밸류_PBR',
             '퀄리티_ROE', '퀄리티_매출증가', '퀄리티_영업이익증가', '퀄리티_순이익증가',
             '종합점수', '종합순위', '종합순위_퍼센트']

# 역발상 전략 적용 (밸류+모멘텀 조합)
data = mf_kr.get_score_adj_weight(df, weight='역발상')

# 최상위 5종목 출력
data[cols].head()

,scode,sname,모멘텀_주가,모멘텀_거래량,밸류_PER,밸류_PBR,퀄리티_ROE,퀄리티_매출증가,퀄리티_영업이익증가,퀄리티_순이익증가,종합점수,종합순위,종합순위_퍼센트
0,267250,HD현대,25.252525,27.272727,3.030303,7.575758,27.272727,61.616162,33.333333,19.191919,15.782828,1.0,1.010101
1,010060,OCI홀딩스,2.020202,6.060606,50.505051,10.101010,92.929293,86.868687,93.939394,86.868687,17.171717,2.0,2.020202
2,034730,SK,30.303030,36.363636,7.070707,2.020202,78.787879,81.818182,80.808081,93.939394,18.939394,3.0,3.030303
3,000990,DB하이텍,13.131313,4.040404,29.292929,47.474747,30.303030,59.595960,59.595960,60.606061,23.484848,4.0,4.040404
4,006400,삼성SDI,17.171717,11.111111,50.505051,38.383838,91.919192,22.222222,70.707071,98.989899,29.292929,5.0,5.050505